
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author uf1185hd
 */
public class BingoMenu extends javax.swing.JFrame {

    GameDetails gd = GameDetails.getInstance();

    /**
     * Creates new form BingoMenu
     */
    public BingoMenu() {

        initComponents();
        //Center the Jframe
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        blackOut = new javax.swing.JButton();
        xGame = new javax.swing.JButton();
        regular = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        blackOut.setText("BlackOut");
        blackOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blackOutActionPerformed(evt);
            }
        });

        xGame.setText("X");
        xGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xGameActionPerformed(evt);
            }
        });

        regular.setText("Regular");
        regular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regularActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BingoLogo.jpeg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(blackOut, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xGame, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regular, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(blackOut, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xGame, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regular, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void blackOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blackOutActionPerformed
        gd.setGameType(2);
        requestNumberOfPlayers();

        // TODO add your handling code here:
        this.setVisible(false);
        BingoWindow bingo = new BingoWindow();
        bingo.setVisible(true);


    }//GEN-LAST:event_blackOutActionPerformed

    private void xGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xGameActionPerformed
        gd.setGameType(1);
        requestNumberOfPlayers();
        // TODO add your handling code here:

        this.setVisible(false);
        BingoWindow bingo = new BingoWindow();
        bingo.setVisible(true);


    }//GEN-LAST:event_xGameActionPerformed

    private void regularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regularActionPerformed
        gd.setGameType(0);
        requestNumberOfPlayers();

        // TODO add your handling code here:
        this.setVisible(false);
        BingoWindow bingo = new BingoWindow();
        bingo.setVisible(true);


    }//GEN-LAST:event_regularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BingoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BingoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BingoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BingoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BingoMenu().setVisible(true);
            }
        });
    }

    public void requestNumberOfPlayers() {
        boolean validEntry = true;
        while (validEntry) {
            try {

                // string is parsed to an int
                // if it isn't an int, then it sends to exception and redos loop
                Integer numberOfPlayers = Integer.parseInt(JOptionPane.showInputDialog(this, "Number of Players to play against: "));

                gd.setNumberOfPlayers(numberOfPlayers + 1);
                // set number of players, must be 2 or more players
                if (gd.getNumberOfPlayers() > 1) {
                    validEntry = false;
                } else {
                    validEntry = true;
                }

            } catch (Exception InvalidEntry) {

                System.out.println("EXCEPTION: Invalid Entry!\n");
            }

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blackOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton regular;
    private javax.swing.JButton xGame;
    // End of variables declaration//GEN-END:variables
}
